set -g prefix C-a
unbind C-b
bind C-a send-prefix

bind -n M-Left      previous-window
bind -n M-Right     next-window
bind -n M-,         previous-window
bind -n M-.         next-window
bind -n M-q         kill-pane
bind -n M-Q         confirm-before -p "kill-window #W? (y/n)" kill-window
bind -n M-c         new-window -c "#{pane_current_path}"

bind -n M-h         select-pane -L
bind -n M-j         select-pane -D
bind -n M-k         select-pane -U
bind -n M-l         select-pane -R

bind -n M-v         split-window -h -c "#{pane_current_path}"
bind -n M-s         split-window -v -c "#{pane_current_path}"

set -g default-terminal "tmux-256color"
set -as terminal-overrides ",st-256color:Tc"
set -s escape-time 0
set -g history-limit 200000
set -g mouse on
setw -g mode-keys vi
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g focus-events on
set -g status-interval 5
setw -g monitor-activity off
setw -g monitor-bell off
set -g activity-action none
set -g bell-action none
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g aggressive-resize on

bind r source-file ~/.config/tmux/tmux.conf \; display "reloaded"

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"

bind-key -n DoubleClick1Pane \
	select-pane \; \
	copy-mode -M \; \
	send-keys -X select-word \; \
	send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"

bind-key u capture-pane -J \; \
    split-window -l 10 "tmux save-buffer - | grep -oE \"https?://[a-zA-Z0-9./?=%&_#:~@!$'()*+,;-]+\" | sort -u | fzf --reverse | tr -d '\\n' | xclip -selection clipboard -i"

bind-key U capture-pane -J \; \
    split-window -l 10 "tmux save-buffer - | grep -oE \"https?://[a-zA-Z0-9./?=%&_#:~@!$'()*+,;-]+\" | sort -u | fzf --reverse | xargs -r xdg-open"

set -g set-titles on
set -g set-titles-string "#T"

set -g status-style bg="#272822",fg="#F8F8F2"
set -g status-justify left
set -g status-left-length 20
set -g status-right-length 50

set -g status-left "#[fg=#272822,bg=#A6E22E,bold] #S #[fg=#A6E22E,bg=#272822] "

setw -g window-status-current-format "#[fg=#272822,bg=#F92672]#[fg=#272822,bg=#F92672,bold] #I:#W #[fg=#F92672,bg=#272822]"
setw -g window-status-format "#[fg=#F8F8F2,bg=#272822]  #I:#W  "
setw -g window-status-separator ""

set -g status-right "#[fg=#66D9EF,bg=#272822]#[fg=#272822,bg=#66D9EF,bold] %H:%M "

set -g pane-border-style fg=#3E3D32
set -g pane-active-border-style fg=#A6E22E
